version: "3.9"
services:
  authapp:
    container_name: authapp
    image: net.keithyw.authapp/authapp:latest
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - message-app_backend
    ports:
      - "8082:8082"
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_HOST: ${MYSQL_HOST}
      PORT: ${PORT}      

networks:
  message-app_backend:
    external: true
      